### PR TITLE
Add workflow to run golangci-lint

### PR DESCRIPTION
**Pull request by rubiojr**
The linter config being added is pretty hardcore, we'll need to tune it to our liking and fix the rest.

### CODE REVIEW

**Comment by rubiojr** [comment]
This is looking good now. A breakdown of the issues is printed locally, which we could use to disable linters we don't currently want:

```
1142 issues:
* bodyclose: 3
* contextcheck: 8
* depguard: 146
* dupword: 4
* durationcheck: 1
* errchkjson: 1
* errname: 1
* errorlint: 341
* fatcontext: 2
* forcetypeassert: 46
* gochecknoinits: 23
* gocritic: 22
* gosec: 96
* gosmopolitan: 5
* ineffassign: 6
* intrange: 24
* maintidx: 7
* misspell: 5
* nakedret: 6
* nestif: 41
* nilerr: 2
* noctx: 9
* predeclared: 1
* revive: 273
* sqlclosecheck: 4
* staticcheck: 3
* stylecheck: 43
* unconvert: 1
* unused: 18
```

**Comment by mholt** [comment]
Oh we gonna have the highest quality code base

**Comment by mholt** [comment]
Awesome, thanks!

Will these show up in an editor like VS Code, do you know?

Anyway, this LGTM and I'll probably merge it for now and we can adjust later if needed.

**Comment by rubiojr** [comment]
@mholt not sure tbh, not much of a vscode user myself.

**Comment by mholt** [comment]
No worries. Found my answer!

https://golangci-lint.run/welcome/integrations/

It automatically uses the CI file you created here, so I should be good to go now :+1:

**Pull request merged**
